import wallet from '../../public/wallet.svg';
import vault from '../../public/vault.svg';
import watcher from '../../public/watcher.svg';
import affiliate from '../../public/affiliate.svg';
import avatar from '../../public/avatar.svg';
import bitcoin from '../../public/bitcoin.svg';
import usdt from '../../public/usdt.svg';
import astro from '../../public/astro.svg';

export const sidebarNav = [
  {
    name: 'Wallet',
    icon: wallet,
    id: 1,
    link: '/wallet',
  },
  {
    name: 'Vaults',
    icon: vault,
    id: 2,
    link: '/vault',
  },
  {
    name: 'Affiliate',
    icon: affiliate,
    id: 3,
    link: '/affiliate',
  },
  {
    name: 'Watcher',
    icon: watcher,
    id: 4,
    link: '/watcher',
  },
];

export const vaultData = [
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    vaultStatus: 'In-Active',
    whales: '5',
    focus: 'Small Liquidity',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    type: 'Redistribution',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Pending',
    focus: 'Small Liquidity',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    token: [bitcoin, usdt, astro],
  },
  {
    title: 'Star Vault',
    avatar: avatar,
    trade: '2 Days ago',
    whales: '5',
    vaultStatus: 'Active',
    focus: 'Small Liquidity',
    status: 'Pre Buy',
    funds: 'Pantera Capital',
    token: [bitcoin, usdt, astro],
  },
];

export const walletData = [
  {
    wallet: '10x83838838382823',
    pl: '5786%',
    stableCoin: '45%',
    trade: '1 Week',
    walletSize: '3.4 M',
    transaction: '1 day ago',
    diversification: '30%',
  },
  {
    wallet: '10x83838838382823',
    pl: '5786%',
    stableCoin: '45%',
    trade: '1 Week',
    walletSize: '3.4 M',
    transaction: '1 day ago',
    diversification: '30%',
  },
  {
    wallet: '10x83838838382823',
    pl: '5786%',
    stableCoin: '45%',
    trade: '1 Week',
    walletSize: '3.4 M',
    transaction: '1 day ago',
    diversification: '30%',
  },
];

export const affiliateData = [
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
  {
    name: 'John Doe',
    addedBy: 'Lukas Navickas',
    wallet: '0x505dl8...765',
    amount: '3',
    telegram: '@johndoe',
    community: 'youtube.com/watch?v=vQL44P75RX8',
  },
];

export const watcherData = [
  {
    avatar: avatar,
    title: 'bsc-watcher',
    status: 'Active',
    memory: '20%',
    cpu: '20%',
    id: '758293',
    instances: '1',
  },
  {
    avatar: avatar,
    title: 'bsc-watcher',
    status: 'Active',
    memory: '20%',
    cpu: '20%',
    id: '758293',
    instances: '1',
  },
  {
    avatar: avatar,
    title: 'bsc-watcher',
    status: 'In-active',
    memory: '20%',
    cpu: '20%',
    id: '758293',
    instances: '1',
  },
  {
    avatar: avatar,
    title: 'bsc-watcher',
    status: 'Pending',
    memory: '20%',
    cpu: '20%',
    id: '758293',
    instances: '1',
  },
];

export const walletAddresses = [
  '0x5058352e527694a5549661542234234aslkdf3234j',
  '0x5058352e527694a5549661542234234aslkdf32390',
  '0x5058352e527694a5549661542234234aslkdf32320',
];

export const tokenIcons = [bitcoin, usdt, astro];

export const vaultHeadings = ['Name', 'Last Trade', 'Whales', 'Status', 'Tokens', 'Funds', 'Focus', ''];
